### ISSUE TITLE
mondrian tutorial doesn't work - graphics issues

### ISSUE THREAD

**Issue by hom3mad3** [rust-community/rustbridge#58]
Hello everyone, I ran into a couple of issues while trying the tutorial:

```ssh
$ cargo run
Running `target/debug/mondpaint`
paint_rectangle: 20, 20, 300, 250
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: DescriptorInit(PixelExport(0, None))', ../src/libcore/result.rs:788

note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:788
error: Process didn't exit successfully: `target/debug/mondpaint` (exit code: 101)
```

I'm running on Ubuntu 16.04 LTS 64-bit and I already tried switching to OpenGL::V2_1 

```rust
// Change this to OpenGL::V2_1 if not working.
        let opengl = OpenGL::V1_2;
```

**Comment by hom3mad3** [comment]
although i thought this could be an interesting issue at first, i see that this might be also very limited to older machines only (which i don't recommend for trying this tutorial).

**Comment by broesamle** [comment]
if I understand correctly this is different from #56

**Comment by broesamle** [comment]
https://github.com/SLMT/rust-ogldev
nave not yet looked into it but it might help...
